terraform {
  required_version = ">= 1.5.0"
}

# Auto-generated by gen.py for REPRO-20260626-037 (ZD-116501 OPA large-plan skip).
# 10 resources x 24 attrs x ~24000 chars => ~110 MB plan_human.
# The filler is defined once and reused so the source stays small; the plan
# renders the resolved value per attribute, inflating plan_human past 100 MB.

locals {
  filler_base = "LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-LARGEPLAN-"
  filler      = join("", [for i in range(240) : local.filler_base])
}

resource "terraform_data" "bulk_0000" {
  input = {
    attr_00 = "${local.filler}-r0000-a00"
    attr_01 = "${local.filler}-r0000-a01"
    attr_02 = "${local.filler}-r0000-a02"
    attr_03 = "${local.filler}-r0000-a03"
    attr_04 = "${local.filler}-r0000-a04"
    attr_05 = "${local.filler}-r0000-a05"
    attr_06 = "${local.filler}-r0000-a06"
    attr_07 = "${local.filler}-r0000-a07"
    attr_08 = "${local.filler}-r0000-a08"
    attr_09 = "${local.filler}-r0000-a09"
    attr_10 = "${local.filler}-r0000-a10"
    attr_11 = "${local.filler}-r0000-a11"
    attr_12 = "${local.filler}-r0000-a12"
    attr_13 = "${local.filler}-r0000-a13"
    attr_14 = "${local.filler}-r0000-a14"
    attr_15 = "${local.filler}-r0000-a15"
    attr_16 = "${local.filler}-r0000-a16"
    attr_17 = "${local.filler}-r0000-a17"
    attr_18 = "${local.filler}-r0000-a18"
    attr_19 = "${local.filler}-r0000-a19"
    attr_20 = "${local.filler}-r0000-a20"
    attr_21 = "${local.filler}-r0000-a21"
    attr_22 = "${local.filler}-r0000-a22"
    attr_23 = "${local.filler}-r0000-a23"
  }
}

resource "terraform_data" "bulk_0001" {
  input = {
    attr_00 = "${local.filler}-r0001-a00"
    attr_01 = "${local.filler}-r0001-a01"
    attr_02 = "${local.filler}-r0001-a02"
    attr_03 = "${local.filler}-r0001-a03"
    attr_04 = "${local.filler}-r0001-a04"
    attr_05 = "${local.filler}-r0001-a05"
    attr_06 = "${local.filler}-r0001-a06"
    attr_07 = "${local.filler}-r0001-a07"
    attr_08 = "${local.filler}-r0001-a08"
    attr_09 = "${local.filler}-r0001-a09"
    attr_10 = "${local.filler}-r0001-a10"
    attr_11 = "${local.filler}-r0001-a11"
    attr_12 = "${local.filler}-r0001-a12"
    attr_13 = "${local.filler}-r0001-a13"
    attr_14 = "${local.filler}-r0001-a14"
    attr_15 = "${local.filler}-r0001-a15"
    attr_16 = "${local.filler}-r0001-a16"
    attr_17 = "${local.filler}-r0001-a17"
    attr_18 = "${local.filler}-r0001-a18"
    attr_19 = "${local.filler}-r0001-a19"
    attr_20 = "${local.filler}-r0001-a20"
    attr_21 = "${local.filler}-r0001-a21"
    attr_22 = "${local.filler}-r0001-a22"
    attr_23 = "${local.filler}-r0001-a23"
  }
}

resource "terraform_data" "bulk_0002" {
  input = {
    attr_00 = "${local.filler}-r0002-a00"
    attr_01 = "${local.filler}-r0002-a01"
    attr_02 = "${local.filler}-r0002-a02"
    attr_03 = "${local.filler}-r0002-a03"
    attr_04 = "${local.filler}-r0002-a04"
    attr_05 = "${local.filler}-r0002-a05"
    attr_06 = "${local.filler}-r0002-a06"
    attr_07 = "${local.filler}-r0002-a07"
    attr_08 = "${local.filler}-r0002-a08"
    attr_09 = "${local.filler}-r0002-a09"
    attr_10 = "${local.filler}-r0002-a10"
    attr_11 = "${local.filler}-r0002-a11"
    attr_12 = "${local.filler}-r0002-a12"
    attr_13 = "${local.filler}-r0002-a13"
    attr_14 = "${local.filler}-r0002-a14"
    attr_15 = "${local.filler}-r0002-a15"
    attr_16 = "${local.filler}-r0002-a16"
    attr_17 = "${local.filler}-r0002-a17"
    attr_18 = "${local.filler}-r0002-a18"
    attr_19 = "${local.filler}-r0002-a19"
    attr_20 = "${local.filler}-r0002-a20"
    attr_21 = "${local.filler}-r0002-a21"
    attr_22 = "${local.filler}-r0002-a22"
    attr_23 = "${local.filler}-r0002-a23"
  }
}

resource "terraform_data" "bulk_0003" {
  input = {
    attr_00 = "${local.filler}-r0003-a00"
    attr_01 = "${local.filler}-r0003-a01"
    attr_02 = "${local.filler}-r0003-a02"
    attr_03 = "${local.filler}-r0003-a03"
    attr_04 = "${local.filler}-r0003-a04"
    attr_05 = "${local.filler}-r0003-a05"
    attr_06 = "${local.filler}-r0003-a06"
    attr_07 = "${local.filler}-r0003-a07"
    attr_08 = "${local.filler}-r0003-a08"
    attr_09 = "${local.filler}-r0003-a09"
    attr_10 = "${local.filler}-r0003-a10"
    attr_11 = "${local.filler}-r0003-a11"
    attr_12 = "${local.filler}-r0003-a12"
    attr_13 = "${local.filler}-r0003-a13"
    attr_14 = "${local.filler}-r0003-a14"
    attr_15 = "${local.filler}-r0003-a15"
    attr_16 = "${local.filler}-r0003-a16"
    attr_17 = "${local.filler}-r0003-a17"
    attr_18 = "${local.filler}-r0003-a18"
    attr_19 = "${local.filler}-r0003-a19"
    attr_20 = "${local.filler}-r0003-a20"
    attr_21 = "${local.filler}-r0003-a21"
    attr_22 = "${local.filler}-r0003-a22"
    attr_23 = "${local.filler}-r0003-a23"
  }
}

resource "terraform_data" "bulk_0004" {
  input = {
    attr_00 = "${local.filler}-r0004-a00"
    attr_01 = "${local.filler}-r0004-a01"
    attr_02 = "${local.filler}-r0004-a02"
    attr_03 = "${local.filler}-r0004-a03"
    attr_04 = "${local.filler}-r0004-a04"
    attr_05 = "${local.filler}-r0004-a05"
    attr_06 = "${local.filler}-r0004-a06"
    attr_07 = "${local.filler}-r0004-a07"
    attr_08 = "${local.filler}-r0004-a08"
    attr_09 = "${local.filler}-r0004-a09"
    attr_10 = "${local.filler}-r0004-a10"
    attr_11 = "${local.filler}-r0004-a11"
    attr_12 = "${local.filler}-r0004-a12"
    attr_13 = "${local.filler}-r0004-a13"
    attr_14 = "${local.filler}-r0004-a14"
    attr_15 = "${local.filler}-r0004-a15"
    attr_16 = "${local.filler}-r0004-a16"
    attr_17 = "${local.filler}-r0004-a17"
    attr_18 = "${local.filler}-r0004-a18"
    attr_19 = "${local.filler}-r0004-a19"
    attr_20 = "${local.filler}-r0004-a20"
    attr_21 = "${local.filler}-r0004-a21"
    attr_22 = "${local.filler}-r0004-a22"
    attr_23 = "${local.filler}-r0004-a23"
  }
}

resource "terraform_data" "bulk_0005" {
  input = {
    attr_00 = "${local.filler}-r0005-a00"
    attr_01 = "${local.filler}-r0005-a01"
    attr_02 = "${local.filler}-r0005-a02"
    attr_03 = "${local.filler}-r0005-a03"
    attr_04 = "${local.filler}-r0005-a04"
    attr_05 = "${local.filler}-r0005-a05"
    attr_06 = "${local.filler}-r0005-a06"
    attr_07 = "${local.filler}-r0005-a07"
    attr_08 = "${local.filler}-r0005-a08"
    attr_09 = "${local.filler}-r0005-a09"
    attr_10 = "${local.filler}-r0005-a10"
    attr_11 = "${local.filler}-r0005-a11"
    attr_12 = "${local.filler}-r0005-a12"
    attr_13 = "${local.filler}-r0005-a13"
    attr_14 = "${local.filler}-r0005-a14"
    attr_15 = "${local.filler}-r0005-a15"
    attr_16 = "${local.filler}-r0005-a16"
    attr_17 = "${local.filler}-r0005-a17"
    attr_18 = "${local.filler}-r0005-a18"
    attr_19 = "${local.filler}-r0005-a19"
    attr_20 = "${local.filler}-r0005-a20"
    attr_21 = "${local.filler}-r0005-a21"
    attr_22 = "${local.filler}-r0005-a22"
    attr_23 = "${local.filler}-r0005-a23"
  }
}

resource "terraform_data" "bulk_0006" {
  input = {
    attr_00 = "${local.filler}-r0006-a00"
    attr_01 = "${local.filler}-r0006-a01"
    attr_02 = "${local.filler}-r0006-a02"
    attr_03 = "${local.filler}-r0006-a03"
    attr_04 = "${local.filler}-r0006-a04"
    attr_05 = "${local.filler}-r0006-a05"
    attr_06 = "${local.filler}-r0006-a06"
    attr_07 = "${local.filler}-r0006-a07"
    attr_08 = "${local.filler}-r0006-a08"
    attr_09 = "${local.filler}-r0006-a09"
    attr_10 = "${local.filler}-r0006-a10"
    attr_11 = "${local.filler}-r0006-a11"
    attr_12 = "${local.filler}-r0006-a12"
    attr_13 = "${local.filler}-r0006-a13"
    attr_14 = "${local.filler}-r0006-a14"
    attr_15 = "${local.filler}-r0006-a15"
    attr_16 = "${local.filler}-r0006-a16"
    attr_17 = "${local.filler}-r0006-a17"
    attr_18 = "${local.filler}-r0006-a18"
    attr_19 = "${local.filler}-r0006-a19"
    attr_20 = "${local.filler}-r0006-a20"
    attr_21 = "${local.filler}-r0006-a21"
    attr_22 = "${local.filler}-r0006-a22"
    attr_23 = "${local.filler}-r0006-a23"
  }
}

resource "terraform_data" "bulk_0007" {
  input = {
    attr_00 = "${local.filler}-r0007-a00"
    attr_01 = "${local.filler}-r0007-a01"
    attr_02 = "${local.filler}-r0007-a02"
    attr_03 = "${local.filler}-r0007-a03"
    attr_04 = "${local.filler}-r0007-a04"
    attr_05 = "${local.filler}-r0007-a05"
    attr_06 = "${local.filler}-r0007-a06"
    attr_07 = "${local.filler}-r0007-a07"
    attr_08 = "${local.filler}-r0007-a08"
    attr_09 = "${local.filler}-r0007-a09"
    attr_10 = "${local.filler}-r0007-a10"
    attr_11 = "${local.filler}-r0007-a11"
    attr_12 = "${local.filler}-r0007-a12"
    attr_13 = "${local.filler}-r0007-a13"
    attr_14 = "${local.filler}-r0007-a14"
    attr_15 = "${local.filler}-r0007-a15"
    attr_16 = "${local.filler}-r0007-a16"
    attr_17 = "${local.filler}-r0007-a17"
    attr_18 = "${local.filler}-r0007-a18"
    attr_19 = "${local.filler}-r0007-a19"
    attr_20 = "${local.filler}-r0007-a20"
    attr_21 = "${local.filler}-r0007-a21"
    attr_22 = "${local.filler}-r0007-a22"
    attr_23 = "${local.filler}-r0007-a23"
  }
}

resource "terraform_data" "bulk_0008" {
  input = {
    attr_00 = "${local.filler}-r0008-a00"
    attr_01 = "${local.filler}-r0008-a01"
    attr_02 = "${local.filler}-r0008-a02"
    attr_03 = "${local.filler}-r0008-a03"
    attr_04 = "${local.filler}-r0008-a04"
    attr_05 = "${local.filler}-r0008-a05"
    attr_06 = "${local.filler}-r0008-a06"
    attr_07 = "${local.filler}-r0008-a07"
    attr_08 = "${local.filler}-r0008-a08"
    attr_09 = "${local.filler}-r0008-a09"
    attr_10 = "${local.filler}-r0008-a10"
    attr_11 = "${local.filler}-r0008-a11"
    attr_12 = "${local.filler}-r0008-a12"
    attr_13 = "${local.filler}-r0008-a13"
    attr_14 = "${local.filler}-r0008-a14"
    attr_15 = "${local.filler}-r0008-a15"
    attr_16 = "${local.filler}-r0008-a16"
    attr_17 = "${local.filler}-r0008-a17"
    attr_18 = "${local.filler}-r0008-a18"
    attr_19 = "${local.filler}-r0008-a19"
    attr_20 = "${local.filler}-r0008-a20"
    attr_21 = "${local.filler}-r0008-a21"
    attr_22 = "${local.filler}-r0008-a22"
    attr_23 = "${local.filler}-r0008-a23"
  }
}

resource "terraform_data" "bulk_0009" {
  input = {
    attr_00 = "${local.filler}-r0009-a00"
    attr_01 = "${local.filler}-r0009-a01"
    attr_02 = "${local.filler}-r0009-a02"
    attr_03 = "${local.filler}-r0009-a03"
    attr_04 = "${local.filler}-r0009-a04"
    attr_05 = "${local.filler}-r0009-a05"
    attr_06 = "${local.filler}-r0009-a06"
    attr_07 = "${local.filler}-r0009-a07"
    attr_08 = "${local.filler}-r0009-a08"
    attr_09 = "${local.filler}-r0009-a09"
    attr_10 = "${local.filler}-r0009-a10"
    attr_11 = "${local.filler}-r0009-a11"
    attr_12 = "${local.filler}-r0009-a12"
    attr_13 = "${local.filler}-r0009-a13"
    attr_14 = "${local.filler}-r0009-a14"
    attr_15 = "${local.filler}-r0009-a15"
    attr_16 = "${local.filler}-r0009-a16"
    attr_17 = "${local.filler}-r0009-a17"
    attr_18 = "${local.filler}-r0009-a18"
    attr_19 = "${local.filler}-r0009-a19"
    attr_20 = "${local.filler}-r0009-a20"
    attr_21 = "${local.filler}-r0009-a21"
    attr_22 = "${local.filler}-r0009-a22"
    attr_23 = "${local.filler}-r0009-a23"
  }
}

