#!/usr/bin/env python3
"""Generate a compact Terraform/OpenTofu config whose plan_human (text plan)
exceeds the IaCM OPA large-file skip threshold (>100 MB), to reproduce ZD-116501.

Strategy: define one large filler string ONCE as a local, then reference it from
many `terraform_data` resources (builtin provider, no cloud creds). The plan diff
renders the *resolved* value for every attribute, so plan_human balloons while the
source file stays small. Mirrors iHerb's "full structs in stripIrrelevantDrift"
plan_human at ~114 MB.

argv: count attrs_per_resource chars_per_attr
"""
import sys

COUNT = int(sys.argv[1]) if len(sys.argv) > 1 else 190
ATTRS = int(sys.argv[2]) if len(sys.argv) > 2 else 24
CHARS = int(sys.argv[3]) if len(sys.argv) > 3 else 24000

print('terraform {')
print('  required_version = ">= 1.5.0"')
print('}')
print()
print('# Auto-generated by gen.py for REPRO-20260626-037 (ZD-116501 OPA large-plan skip).')
print(f'# {COUNT} resources x {ATTRS} attrs x ~{CHARS} chars => ~110 MB plan_human.')
print('# The filler is defined once and reused so the source stays small; the plan')
print('# renders the resolved value per attribute, inflating plan_human past 100 MB.')
print()
# range() is capped at 1024 in OpenTofu/Terraform, so build the filler from a
# 100-char base chunk repeated (CHARS/100) times (kept under the 1024 limit).
base_chunk = "LARGEPLAN-" * 10  # 100 chars
reps = max(1, CHARS // 100)
print('locals {')
print(f'  filler_base = "{base_chunk}"')
print(f'  filler      = join("", [for i in range({reps}) : local.filler_base])')
print('}')
print()

for i in range(COUNT):
    print(f'resource "terraform_data" "bulk_{i:04d}" {{')
    print('  input = {')
    for a in range(ATTRS):
        print(f'    attr_{a:02d} = "${{local.filler}}-r{i:04d}-a{a:02d}"')
    print('  }')
    print('}')
    print()
